# Generated by Django 3.2.8 on 2021-10-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_edited_by',
            field=models.CharField(default='Testing', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('processing', 'processing'), ('on-hold', 'on-hold'), ('payment confirmed', 'payment confirmed'), ('order paid', 'order-paid'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('failed', 'failed'), ('trash', 'trash')], max_length=50),
        ),
    ]
