# Generated by Django 3.2.8 on 2021-10-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='role',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Processing', 'Processing'), ('Packaging', 'Packaging'), ('Delivery', 'Delivery'), ('Admin', 'Admin')], default='Processing', max_length=50),
        ),
    ]
